# Generated by Django 2.1.4 on 2018-12-21 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mycustomusers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Adresi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiflik Durumu')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2018, 12, 21, 22, 7, 7, 489025, tzinfo=utc), verbose_name='Katılma Tarihi')),
                ('last_activated', models.DateTimeField(blank=True, verbose_name='Son Aktif Edilme Tarihi')),
                ('last_deactivated', models.DateTimeField(blank=True, verbose_name='Son Pasif Edilme Tarihi')),
                ('employee_type', models.PositiveSmallIntegerField(choices=[(1, 'Müşteri Temsilcisi'), (2, 'Teknik Servis Görevlisi')], verbose_name='Hesap Türü')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin Yetkilendirmesi')),
            ],
            options={
                'verbose_name': 'çalışan',
                'verbose_name_plural': 'çalışanlar',
            },
            managers=[
                ('objects', mycustomusers.models.EmployeeManager()),
            ],
        ),
    ]
