# Generated by Django 2.1.4 on 2018-12-21 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mycustomusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 22, 14, 14, 398149, tzinfo=utc), verbose_name='Katılma Tarihi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Yönetici'), (1, 'Müşteri Temsilcisi'), (2, 'Teknik Servis Görevlisi')], verbose_name='Hesap Türü'),
        ),
    ]
