# Generated by Django 2.1.4 on 2018-12-21 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mycustomusers', '0003_auto_20181222_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 22, 24, 43, 479851, tzinfo=utc), verbose_name='Katılma Tarihi'),
        ),
    ]
