# Generated by Django 2.1.4 on 2018-12-21 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycustomusers', '0004_auto_20181222_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Katılma Tarihi'),
        ),
    ]
