# Generated by Django 2.1.4 on 2018-12-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycustomusers', '0005_auto_20181222_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_activated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Aktif Edilme Tarihi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_deactivated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Pasif Edilme Tarihi'),
        ),
    ]
