# Generated by Django 2.1.4 on 2018-12-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_id', models.IntegerField(unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_compliant', models.CharField(max_length=500)),
                ('recieved_at', models.DateTimeField(auto_now_add=True, verbose_name='Ürün kayıt tarihi')),
                ('repaired_at', models.DateTimeField(blank=True, null=True, verbose_name='Onarılma tarihi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim tarihi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
    ]
