# Generated by Django 2.1.3 on 2018-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='civil_id',
            field=models.IntegerField(unique=True),
        ),
    ]
