# Generated by Django 2.1.4 on 2018-12-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181211_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Device',
        ),
    ]
